source 'https://rubygems.org'

gem 'allure-cucumber'
gem 'capybara', '~> 3.35.2'
gem 'capybara-playwright-driver'
gem 'cucumber'
gem 'ffi', '~> 1.15', '>= 1.15.4'
gem 'rspec', '3.7.0'
gem 'selenium-webdriver', '~> 3.5'
gem 'rexml'
gem 'rspec-retry'
