name: Test com Capybara e Playwright

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 5"

jobs:
  test:
    name: Playwright@${{ matrix.browser}} ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        browser: [chromium, webkit, firefox]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install operating system dependencies
        run:  sudo apt-get install xvfb |
              export DISPLAY=:0.0
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: ${{ matrix.firefox }}
      - run: firefox --version
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: microsoft/playwright-github-action@v1
      - name: setup playwright via npm install
        run: |
          export PLAYWRIGHT_CLI_VERSION=$(bundle exec ruby -e 'require "playwright"; puts Playwright::COMPATIBLE_PLAYWRIGHT_VERSION.strip')
          npm install playwright@${PLAYWRIGHT_CLI_VERSION} || npm install playwright@next
          ./node_modules/.bin/playwright install
      - run: npm install -g allure-commandline --save-dev |
             bundler install |
             bundle exec cucumber
        env:
          BROWSER: ${{ matrix.browser }}
          HEADLESS: true
          PLAYWRIGHT_CLI_EXECUTABLE_PATH: ./node_modules/.bin/playwright
        timeout-minutes: 30
          
      - name: 📊 Step 5 - Collect Allure files and generate allure-report folder
        run: |
          allure generate report/allure-results -o ./allure-report/${{ matrix.browser }}
          
      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: allure-report/${{ matrix.browser }}
          destination_dir: ${{ matrix.browser}}
