name: Test com Capybara e Playwright

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 5"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: [2.6]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install operating system dependencies
        run:  sudo apt-get install xvfb |
              sudo apt-get install -y libdbus-glib-1-2 |
              export DISPLAY=:99.0
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: ${{ matrix.firefox }}
      - run: firefox --version
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install operating system dependencies
        run: |
             npx playwright install --with-deps |
             npm install playwright@next --save-dev |
             npm install -g allure-commandline --save-dev
      - name: Install operating system dependencies
        run: ./node_modules/.bin/playwright install

      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        # uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: |
             ls
             bundler install
             bundle exec cucumber
          
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: report/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
